# Spring Profile
# active? ??? ??? ??
# ???? ?? ? application-{active}.yml ??? ??? ??
spring:
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: org.ho.cqrs.product.query.dto

#spring:
#  datasource:
#    driver-class-name: {driver class}
#    url: jdbc:mariadb://[ip]:{port}/{database}
#    username: {user}
#    password: {password}
#
#image:
#  image-dir: {??? ?? ?? ??}
#  image-url: {??? ?? URL}